### ISSUE TITLE
Permission bug

### ISSUE THREAD

**Issue by LuluxClient** [Auxilor/Talismans#13]
**Describe the bug**
Hey an issue i'm getting is if I put the permission `"talismans.fromtable.*" `to false on the lowest group and on a higher group I give the permission to craft the "alchemy_1" talisman it won't work. Maybe `talismans.fromtable.*` is overriding everything. After trying to put the permission to craft the "alchemy_1" talisman on false it will still override it and I won't be able to craft it. 

**To Reproduce**
1. Give the permission talismans.fromtable.* on false for the lowest group you have (weight)
2. On a higher group give the permission to craft a certain talisman
3. Try and craft it and it will not work
4. Vice versa if you try to put the specific talisman craft permission on false it won't work. 

**Expected behavior**
I should be able to craft it.

**Screenshots**
none

**Server Information (please complete the following information):**
- Version: This server is running Paper version git-Paper-409 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: c53577e on ver/1.17.1)
You are running the latest version
- Version of plugin and eco (`/ver eco`, `/ver <plugin>`)
Eco: 6.25.2
Talismans:  5.27.0

**Additional context**

**Comment by WillFP** [comment]
Should be fixed in latest

**Comment by LuluxClient** [comment]
> Should be fixed in latest

Not fixed on latest versions. I can't even craft it now even with the permission

**Comment by LuluxClient** [comment]
The only permission working is the talismans.fromtable.*

**Comment by WillFP** [comment]
Should now be fixed again
