### ISSUE TITLE
Talismans not displaying properly in Auction House

### ISSUE THREAD

**Issue by CapitalistCow** [Auxilor/Talismans#24]
**Describe the bug**
Talismans don't display properly inside of Auction House GUI. Normally items should display price, listing time, and seller, but talismans only display as they would normally inside your inventory.
(Also happens with mob heads from Eco enchants beheading enchantment)

**To Reproduce**
1. Install Auction House plugin (https://www.spigotmc.org/resources/auctionhouse.61836/)
2. List a talisman (or eco mob head) on the auction house using "/ah list [price]" while holding the item
3. Use /ah to view the auction house
4. See error (mob heads from enchantment display with the name eco's head)

**Expected behavior**
When you list the item it should display with price, and info on how to click.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/100172484/163081096-07751467-b88c-4066-b589-db44b45b6716.png)
![Capture](https://user-images.githubusercontent.com/100172484/163081307-498e6e41-b6ff-4ad8-8662-d4ba44ae15b8.PNG)

**Server Information:**
- Paper version git-Paper-277 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 87e11bf)
- Eco version 6.31.3
- Talismans version 5.12.2
- EcoEnchants version 8.55.0

**Comment by WillFP** [comment]
Your talismans version is several months out of date, this has been fixed a long time ago

**Comment by CapitalistCow** [comment]
> Your talismans version is several months out of date, this has been fixed a long time ago

I have since updated to the newest version and it is still happening. I'm on 5.42.0.
